// Kurs_Tworzenie_aplikacji_frontendowych/lista11/vite-project/src/TodoList.tsx
import React, { useState } from 'react';
import { v4 as uuid } from 'uuid';

interface Todo {
  id: string;
  task: string;
  isCompleted: boolean;
}


const TodoList: React.FC = () => {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [task, setTask] = useState('');
  const [counter, setCounter] = useState(0);

  const AddTodo = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();//????
    if (task.trim()) {
      setTodos(todos=>[...todos, { id: uuid(), task, isCompleted: false }]);
      setTask('');
      setCounter(counter + 1);
    }
  };

  const CompleteTodo = (id: string) => {
    setTodos(
      todos.map((todo) => {
        if (todo.id === id) {
          todo.isCompleted ? setCounter(counter + 1) : setCounter(counter - 1);
          return { id: todo.id, task: todo.task, isCompleted: !todo.isCompleted };
        }
        return todo;
      }),
    );
  };

  const RemoveTodo = (id: string) => {
    let t = todos.filter((todo) => todo.id == id);
    if (!t[0].isCompleted) setCounter(counter - 1);
    setTodos(todos.filter((todo) => todo.id !== id));
  };

  const RemoveAll = () => {
    setTodos([]);
    setCounter(0);
  };


  return (
    <div>
        <p id="sum">last: {counter}</p>
        <button onClick={() => RemoveAll()}>Remove all</button>
      <form onSubmit={AddTodo}>
        <input
          type="text"
          value={task}
          onChange={(event) => setTask(event.target.value)}
        />
        <button type="submit">Add Todo</button>
      </form>
      <ul>
        {todos.map((todo) => (
          <li key={todo.id}>
            <span style={{textDecoration: todo.isCompleted ? 'line-through' : 'none',}}>
              {todo.task}
            </span>
            <button onClick={() => CompleteTodo(todo.id)}>
              {todo.isCompleted ? 'Mark as Incomplete' : 'Mark as Complete'}
            </button>
            <button onClick={() => RemoveTodo(todo.id)}>Remove</button>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default TodoList;

// Kurs_Tworzenie_aplikacji_frontendowych/lista12/vue-project/src/components/TodoList.vue
<script setup lang="ts">
import TodoItem from "./TodoItem.vue";
import { ref } from "vue";
import { v4 as uuid } from 'uuid';

const tasks = ref([
  { id: uuid(), name: "task1", isCompleted: false},
  { id: uuid(), name: "task2", isCompleted: false},
  { id: uuid(), name: "task3", isCompleted: false},
]);


let counter = 3;
// let text = '';

const removeItem = (id: string) => {
  let t = tasks.value.filter((task) => task.id == id);
  if (!t[0].isCompleted) counter -= 1;
  tasks.value = tasks.value.filter((task) => task.id !== id);
};


const CompleteTodo = (id: string) => {
    tasks.value = tasks.value.map((todo) => {
      if (todo.id === id) {
        todo.isCompleted ? counter += 1 : counter -= 1;
        return { id: todo.id, name: todo.name, isCompleted: !todo.isCompleted };
      }
      return todo;
    });
};


const addTodo = () => {
  tasks.value.push({ id: uuid(), name: newTodo, isCompleted: false });
  newTodo = '';
  counter += 1;
};

const RemoveAll = () => {
    tasks.value = [];
    counter = 0;
  };

let newTodo = '';

</script>

<template>
  <ul>
    <p>last: {{counter}}</p>
    <button @click="RemoveAll">Remove all</button>
    <form @submit.prevent="addTodo">
      <input v-model="newTodo">
      <button>Add Todo</button>    
    </form>
    <TodoItem
      v-for="task in tasks"
      v-bind:key="task.id"
      v-bind:name="task.name"
      v-bind:is-completed="task.isCompleted"
      v-on:remove="removeItem(task.id)"
      v-on:complete="CompleteTodo(task.id)"
    />
  </ul>
</template>
